# - filepath: templates/elite_study1.json
#   synapse_id: syn59199129
# - filepath: templates/elite_long_life.json
#   synapse_id: syn234324324
- filepath: templates/genie.json
  synapse_id: syn63886516